; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Dec 25 2018 20:01:05 GMT-0600 (Central Standard Time)

