; homez.g - for RRF 3
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Dec 25 2018 20:01:04 GMT-0600 (Central Standard Time)
; Edited 8 January 2020

G91             	; relative positioning
G1 H2 Z5 F1000	 	; lift Z relative to current position
G90              	; absolute positioning
G1 X144 Y144 F4000	; go to first probe point
G30              	; home Z by probing the bed
G1 H2 Z5 F400   	; lift Z relative to current position


