; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Dec 25 2018 20:01:04 GMT-0600 (Central Standard Time)
; Edited 23 December 2019
; edited
G91             	; relative positioning
G1 Z5 F600 S2  	 	; lift Z relative to current position
G90              	; absolute positioning
G1 X144 Y144 F4000	; go to first probe point
G30              	; home Z by probing the bed
G1 S2 Z5 F400   	; lift Z relative to current position


